# Site
name: "Prateek Codes Blog"
title: "Prateek Choudhary's Blog"
description: "Tech blog with learnings from Ruby on Rails, React, among other things."
logo: 'assets/images/logo.avif'
favicon: 'assets/images/logo.avif'
baseurl: ""
google_analytics: UA-158773406-2
mailchimp-list:
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  prateek:
    name: Prateek Choudhary
    display_name: Prateek Choudhary
    avatar: 'assets/images/prateek-avatar.avif'
    email: prateekkish@gmail.com
    web: prateekcodes.dev
    twitter: https://twitter.com/prateekkish
    linkedin: https://www.linkedin.com/in/choudharyprateek/
    github: https://github.com/prateekkish
    description: "Senior Software Developer"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination
paginate: 10
paginate_path: /page:num/

# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true
  auto_ids: true

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
