# Site
name: "Prateek Codes Blog"
title: "Prateek Choudhary's Blog"
description: ""
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: ""
google_analytics: 
disqus: 'prateek-codes-blog'
mailchimp-list: 
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  prateek:
    name: Prateek Choudhary
    display_name: Prateek Choudhary
    avatar: 'assets/images/prateek-avatar.jpg'
    email: prateekkish@gmail.com
    web: prateekcodes.dev
    twitter: https://twitter.com/prateekkish
    description: "Software Developer at Saeloun, a Ruby on Rails Consulting & Development Company."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 10
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: 
adsense-data-ad-slot: 

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
