# Site
name: "Prateek Codes - Learn Building Scalable Backend Systems"
title: "Prateek Codes - Building Scalable Backend Systems"
description: "Learn how to build scalable backend systems with Ruby on Rails, PostgreSQL optimization, database scaling, and practical engineering insights from real-world production experiences."
logo: 'assets/images/logo.avif'
favicon: 'assets/images/logo.avif'
baseurl: ""
url: "https://prateekcodes.dev"
google_analytics: UA-158773406-2
mailchimp-list:
include: ["_pages"]
permalink: /:title/

# SEO Tags
twitter:
  username: prateekkish
  card: summary_large_image
social:
  name: Prateek Choudhary
  links:
    - https://x.com/prateekkish
    - https://www.linkedin.com/in/choudharyprateek/
    - https://github.com/prateekkish

# Authors
authors:
  prateek:
    name: Prateek Choudhary
    display_name: Prateek Choudhary
    avatar: 'assets/images/prateek-avatar.avif'
    email: prateekkish@gmail.com
    web: prateekcodes.dev
    twitter: https://x.com/prateekkish
    linkedin: https://www.linkedin.com/in/choudharyprateek/
    github: https://github.com/prateekkish
    description: "Technology Leader"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination
paginate: 10
paginate_path: /page:num/

# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true
  auto_ids: true

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Build Settings
future: true

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
