name: Build Validation

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2.2'
        bundler-cache: true
    
    - name: Install dependencies
      run: |
        gem install bundler:2.6.7
        bundle config set --local deployment 'true'
        bundle install
    
    - name: Build Jekyll site
      run: JEKYLL_ENV=production bundle exec jekyll build
    
    - name: Validate build
      run: |
        if [ ! -d "_site" ]; then
          echo "Build failed: _site directory not found"
          exit 1
        fi
        
        if [ ! -f "_site/index.html" ]; then
          echo "Build failed: index.html not found"
          exit 1
        fi
        
        echo "Build validation passed!"
    
    - name: Check for broken internal links
      run: |
        gem install html-proofer
        htmlproofer ./_site \
          --disable-external \
          --allow-hash-href \
          --ignore-urls "/^#/,/prateekcodes\.dev/" \
          --ignore-files "/assets/js/" \
          --assume-extension ".html"
    
    - name: Upload build artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: jekyll-site
        path: _site/
        retention-days: 7

  # This job will be required for PR merging
  build-status:
    needs: build
    runs-on: ubuntu-latest
    if: always()
    
    steps:
    - name: Build Status Check
      run: |
        if [ "${{ needs.build.result }}" != "success" ]; then
          echo "Build failed! PR cannot be merged."
          exit 1
        fi
        echo "Build passed! PR can be merged."